teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 6.0
    scale_linear_turbo:
      x: 8.0

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0

    # Required for phnx, else the control loop doesn't receive 0 on stopping control
    require_enable_button: false
    enable_button: 2  # Left trigger button
    enable_turbo_button: 5  # Right trigger button
