name: CI

on: [ push, pull_request ]

jobs:
  industrial_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: humble, ROS_REPO: testing, UPSTREAM_WORKSPACE: 'phoenix.repos' }
          - { ROS_DISTRO: humble, ROS_REPO: main, UPSTREAM_WORKSPACE: 'phoenix.repos' }
    name: ROS ${{ matrix.ROS_DISTRO }} (${{ matrix.ROS_REPO }})
    steps:
      - uses: actions/checkout@v3
      - run: sed -i 's/git@github.com:/https:\/\/github.com\//g' phoenix.repos
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
  
